### ISSUE TITLE
device.write(bytes([addr & 0xFF]), stop=False) in sparkfun_qwiickeypad.py

### ISSUE THREAD

**Issue by waseltzer** [fourstix/Sparkfun_CircuitPython_QwiicKeypad#1]
I followed the installation instructions and ran example1, but got an error:
```
pi@raspberrypi:~/Jukebox $ python -V
Python 3.7.3
pi@raspberrypi:~/Jukebox $ sudo python ./example1_read_button.py
Qwicc Keypad Example 1 Read Button
Traceback (most recent call last):
  File "./example1_read_button.py", line 42, in <module>
    if keypad.connected:
  File "/usr/local/lib/python3.7/dist-packages/sparkfun_qwiickeypad.py", line 90, in connected
    if self._read_register(_KEYPAD_ID) != QWIIC_KEYPAD_ADDR:
  File "/usr/local/lib/python3.7/dist-packages/sparkfun_qwiickeypad.py", line 153, in _read_register
    device.write(bytes([addr & 0xFF]), stop=False)
TypeError: write() got an unexpected keyword argument 'stop'
```

**Workaround:** 
/usr/local/lib/python3.7/dist-packages/sparkfun_qwiickeypad.py
change line 153 from:
`device.write(bytes([addr & 0xFF]), stop=False)`
to
`device.write(bytes([addr & 0xFF]))`

**Question:**
Is something wrong with my Python installation? Or, is this a bug?

Note that [Adafruit Bus Device Library Documentation, Release 1.0](https://readthedocs.org/projects/adafruit-circuitpython-busdevice/downloads/pdf/latest/)
does not show any examples using 
`device.write(bytes([addr & 0xFF]), stop=False)`
only:
`device.write(bytes([addr & 0xFF]))`

**Comment by sai-ydev** [comment]
I encountered the same error. Changing it to `device.write(bytes([addr & 0xFF]))` seems to fix the problem.

**Comment by fourstix** [comment]
Thanks, I think the stop variable is no longer supported.  I'll remove it from the code.

**Comment by fourstix** [comment]
This issue is now fixed in the latest release.   The fix was to use the function write_then_readinto() to replace the write() with the stop flag false followed by a readinto().
